version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "build.gradle" }}
           - v1-dependencies-
      - run: ./gradlew dependencies -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew assemble -x signArchives -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD